In [1]:
import numpy as np
a= np.array([12,25,36,20,16])#creating 1d array
print(a)
print(type(a))
# creating 2d array 
a2= np.array([[1,2,3],[5,6,7]])
print('2d array is :\n',a2)
#3d arraay(tensor)
a3= np.array([[1,2,3],[4,5,6],[7,8,9]])
print('3d array is :')
print(a3)

[12 25 36 20 16]
<class 'numpy.ndarray'>
2d array is :
 [[1 2 3]
 [5 6 7]]
3d array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import time
a=[i for i in range(10000)]
b=[i for i in range(10000,20000)]
c=[]
s=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-s)


a1=np.arange(10000)
b1=np.arange(10000,20000)
s1= time.time()
c1=a1+b1
print(time.time()-s1)



0.0
0.011426687240600586


In [6]:
n=np.arange(1,10)
print(n)
m=np.arange(11,20,2)
print(m)

[1 2 3 4 5 6 7 8 9]
[11 13 15 17 19]


In [18]:
#creating the 2d,3d arrays
n1=np.arange(12,24)
n1=n1.reshape((3,4))
print(n1)
print('creating 3d array')
n4=n1.reshape((1,4,3))
print(n4)
print('\n 4d array ')
n5=n4.reshape((1,1,4,3))
print(n5)
print('printing sizes and shapes of the arrays')
print('printing shape of n4:',np.shape(n4))
print("printing the size of n4:", np.size(n4))
print('printing the dimension of n4 :', np.ndim(n4))
print('converting any dimension aray into simple 1d array : \n')
print(n4.flatten())

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
creating 3d array
[[[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

 4d array 
[[[[12 13 14]
   [15 16 17]
   [18 19 20]
   [21 22 23]]]]
printing sizes and shapes of the arrays
printing shape of n4: (1, 4, 3)
printing the size of n4: 12
printing the dimension of n4 : 3
converting any dimension aray into simple 1d array : 

[12 13 14 15 16 17 18 19 20 21 22 23]


In [24]:
#creating the zeroes or ones array of any dimension
z=np.zeros((1,5,2))
print(z)
o=np.ones((5,2))
print(o)
print('printing the identity matrix\n')
i=np.identity(4)
print(i)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
printing the identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [27]:
#scalar operation
c1=np.arange(12).reshape((3,4))
print(c1)
print(f'after adding 1 we get \n{c1+1}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
after adding 1 we get 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
#relationship operator
cl1=np.arange(12).reshape((3,4))
print(cl1)
print(cl1>4)
print(f'mod \n {cl1%2==0}')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
mod 
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
